apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: tu7h83xwx-go 
  janus-idp.io/tekton: tu7h83xwx-go
  backstage.io/kubernetes-id: tu7h83xwx-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tu7h83xwx-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  